---
- name: Create VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load keys file
      include_vars:
        file: keys.yaml
        name: keys
      no_log: True

    - name: Creating VM "{{ hostname }}"
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ keys.vcenter_password }}"
        validate_certs: False
        name: "{{ hostname }}"
        template: "{{ source_template }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        cluster: "{{ cluster_name }}"
        disk:
          - size_gb: "{{ disk1_size }}"
            type: "{{ disk_type }}"
            datastore: "{{ datastore }}"
          - size_gb: "{{ disk2_size }}"
            type: "{{ disk_type }}"
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ ram_memory }}"
          num_cpus: "{{ cpu }}"
          num_cpu_cores_per_socket: "{{ cores }}"
        networks:
          - name: "{{ network_label }}"
            ip: "{{ ip_hostname }}"
            netmask: "{{ subnet }}"
            gateway: "{{ gateway }}"
            type: static
            domain: "{{ guest_domain }}"
            dns_servers: "{{ dns_servers }}"
        customization:
          hostname: "{{ hostname }}"
          dns_servers: "{{ dns_servers }}"
          domain: "{{ guest_domain }}"
          password: "{{ keys.new_vm_password }}"
          joindomain: "{{ guest_domain }}"
          domainadmin: "{{ domain_admin }}"
          domainadminpassword: "{{ keys.admin_password }}"
        wait_for_customization: yes
        wait_for_ip_address: yes
        state: poweredon

    - name: Wait for VMware tools to become available
      vmware_guest_tools_wait:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ keys.vcenter_password }}"
        validate_certs: no
        name: "{{ hostname }}"
      no_log: True

    - name: Waiting for WinRM.........
      wait_for:
        timeout: 25

    - name: Enabling Winrm on "{{ hostname }}"
      vmware_vm_shell:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ keys.vcenter_password }}"
        validate_certs: False
        vm_id: "{{ hostname }}"
        vm_id_type: vm_name
        vm_password: "{{ keys.new_vm_password }}"
        vm_username: administrator
        vm_shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        vm_shell_args: "-File C:\\Script\\ConfigureRemotingForAnsible.ps1"
        wait_for_process: True
      changed_when: false

    - name: Add host to in-memory inventory group
      add_host:
        hostname: "{{ ip_hostname }}"
        groups:
          - new_vm
          - windows

- name: Windows Config....
  hosts: new_vm
  gather_facts: no
  tasks:
    - name: Add user to RDP group
      win_group_membership:
        name: "{{ group_name }}"
        members:
          - "{{ windows_user }}"
        state: present

    - name: Get disks facts
      win_disk_facts:
      no_log: True

    - name: Extend C partition if space available
      win_partition:
        drive_letter: C
        partition_size: -1
      when: size_remaining >= minimum
      vars:
        minimum: "{{ '1 GB' | human_to_bytes }}"
        first_volume: "{{ ansible_disks[0].partitions[0].volumes[0] }}"
        size_remaining: "{{ first_volume.size_remaining }}"

    - name: Initialize disk...
      win_shell: "Initialize-Disk -number 1"
      when: ansible_disks[1].partition_style == 'RAW'

    - name: Create partition
      win_partition:
        drive_letter: D
        partition_size: -1
        disk_number: 1
      when: ansible_disks[1].partitions[1].volumes is undefined

    - name: Format disk
      win_format:
        drive_letter: D
        file_system: NTFS
        new_label: Logs
      when: ansible_disks[1].partition_style == 'RAW'
